application: abrilliantcircle
version: release-1.0
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /js
  static_dir: js

- url: /style
  static_dir: style

- url: /.*
  script: brilliantcircle.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
